import { addIcons } from 'ionicons';
import {
  gridOutline, peopleOutline, alertCircleOutline, starOutline,
  chatbubblesOutline, trophyOutline, documentTextOutline,
  personOutline, homeOutline, logOutOutline, chevronBackOutline,
  chevronForwardOutline, documentOutline, calendarOutline, locationOutline,
  addOutline, filterOutline, informationCircleOutline, checkmarkCircleOutline,
  timeOutline, shieldCheckmarkOutline, mailOutline, lockClosedOutline,
  eyeOutline, eyeOffOutline, schoolOutline, personCircleOutline, folderOpenOutline,
  person, home, chevronDownCircleOutline, layersOutline, logInOutline,
  logIn, logOut, checkmarkCircle, warning, location, refresh, time,
  documentText, addCircle, chevronForward
} from 'ionicons/icons';

// Map specific kebap-case names used in the app to their imported objects
addIcons({
  'grid-outline': gridOutline,
  'people-outline': peopleOutline,
  'alert-circle-outline': alertCircleOutline,
  'star-outline': starOutline,
  'chatbubbles-outline': chatbubblesOutline,
  'trophy-outline': trophyOutline,
  'document-text-outline': documentTextOutline,
  'person-outline': personOutline,
  'home-outline': homeOutline,
  'log-out-outline': logOutOutline,
  'log-in-outline': logInOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'document-outline': documentOutline,
  'calendar-outline': calendarOutline,
  'location-outline': locationOutline,
  'add-outline': addOutline,
  'filter-outline': filterOutline,
  'information-circle-outline': informationCircleOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'time-outline': timeOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'mail-outline': mailOutline,
  'lock-closed-outline': lockClosedOutline,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'school-outline': schoolOutline,
  'person-circle-outline': personCircleOutline,
  'folder-open-outline': folderOpenOutline,
  'chevron-down-circle-outline': chevronDownCircleOutline,
  'layers-outline': layersOutline,
  'person': person,
  'home': home,
  'log-in': logIn,
  'log-out': logOut,
  'checkmark-circle': checkmarkCircle,
  'warning': warning,
  'location': location,
  'refresh': refresh,
  'time': time,
  'document-text': documentText,
  'add-circle': addCircle,
  'chevron-forward': chevronForward
});
